remote_theme: pages-themes/midnight@v0.2.0
plugins:
title: Tyranical Noise of Zephyr
description: Hello, This is my first site and im learning HTML just for this so please bear with me as I will make mistakes. Anyways I shall be refered to as "Zephyr" or "zeph"
